### ISSUE TITLE
Create dependencies

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/SteamValidator#1]
@micwoj92 Do you know anyway to have github use dependencies. I want to spin _GetSteam.au3 and some other Includes to their own repo and have the updated in the other repos automatically, but I'm not sure if this is possible.

**Comment by micwoj92** [comment]
I'm not sure if this is fitting, but git submodules is the closest that comes to my mind at the moment https://www.git-scm.com/docs/gitsubmodules

**Comment by rcmaehl** [comment]
Yeah, looks similar to what I want to do but a bit confusing. I'll see if I can figure it out

**Comment by micwoj92** [comment]
I quickly found out this gist that seems to update submodules via github actions
https://gist.github.com/Supercip971/467846d7b12444275dbb4ac71cc192c4

You could then run that action manually if you used `workflow_dispatch`trigger used in for example wnw11 workflow or set schedule
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule

**Comment by rcmaehl** [comment]
> I quickly found out this gist that seems to update submodules via github actions https://gist.github.com/Supercip971/467846d7b12444275dbb4ac71cc192c4
> 
> You could then run that action manually if you used `workflow_dispatch`trigger used in for example wnw11 workflow or set schedule https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule

I've figured out how to add a submodule. Will setup CI here in a bit.

**Comment by micwoj92** [comment]
Wouldn't it be better to have one repo for all includes? Or maybe categorize them like you did with IRC uds, so for example now it would be"autoit-steam-udfs". Just curious.

**Comment by rcmaehl** [comment]
> Wouldn't it be better to have one repo for all includes? Or maybe categorize them like you did with IRC uds, so for example now it would be"autoit-steam-udfs". Just curious.

All UDFs, no
Categorized UDFs, maybe, probably
